name: Recent blog posts workflow
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update README with recent blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://tugsanunlu.medium.com/feed"
          max_post_count: 10
          comment_tag_name: "RECENT-BLOG-POSTS"
          retry_count: 3
          retry_wait_time: 600
